### ISSUE TITLE
How to get the "init.mat" by my dataset?

### ISSUE THREAD

**Issue by zhangqianqianaa** [Niharika-SD/Deep-sr-DDL#1]
Hi~ i'm training my own dataset on your code, but now i can't get my "init.mat". Can you tell me the the method?
Thanks a lot!

**Comment by Niharika-SD** [comment]
Hi, you can generate an initialisation similar to init.mat by training the model on your data without the prediction term for a couple of iterations (about 20-30) to solve for the basis, coefficients, and constraint terms, as described in the paper. Alternatively, you could try a random initialisation of these variables.

**Comment by zhangqianqianaa** [comment]
Thank you for your reply!I understand
